import { ArrowDown, ArrowUp, ScrollText } from "lucide-react";
import { FeedbackBanner } from "@/components/inventory/feedback-banner";
import { loadMoveHistory } from "@/features/operations/queries";

export const metadata = { title: "Move history" };

export default async function MoveHistoryPage() {
  const { movements, error } = await loadMoveHistory();
  return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Immutable ledger</p><h1 className="mt-1 text-3xl font-extrabold tracking-[-0.04em]">Move history</h1><p className="mt-2 text-sm text-muted-foreground">Every validated stock change, location, resulting balance and source document.</p></header><FeedbackBanner error={error || undefined} /><section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[58rem] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="px-5 py-3">Movement</th><th className="px-5 py-3">Product</th><th className="px-5 py-3">Location</th><th className="px-5 py-3">Document</th><th className="px-5 py-3">Balance after</th><th className="px-5 py-3">Occurred</th></tr></thead><tbody>{movements.map((movement) => { const product = movement.products as unknown as {name:string;sku:string;unit_of_measure:string}|null; const location = movement.locations as unknown as {name:string;warehouses:{name:string}|null}|null; const document = movement.inventory_documents as unknown as {document_number:string;type:string}|null; const delta = Number(movement.quantity_delta); return <tr className="border-b last:border-0" key={movement.id}><td className={`px-5 py-4 font-mono font-bold ${delta > 0 ? "text-emerald-700" : "text-red-600"}`}><span className="inline-flex items-center gap-2">{delta > 0 ? <ArrowUp className="size-4" /> : <ArrowDown className="size-4" />}{delta > 0 ? "+" : ""}{delta.toLocaleString("en-IN")} {product?.unit_of_measure}</span></td><td className="px-5 py-4"><p className="font-bold">{product?.name}</p><p className="font-mono text-xs text-muted-foreground">{product?.sku}</p></td><td className="px-5 py-4"><p className="font-semibold">{location?.name}</p><p className="text-xs text-muted-foreground">{location?.warehouses?.name}</p></td><td className="px-5 py-4"><p className="font-mono text-xs font-bold">{document?.document_number}</p><p className="text-xs capitalize text-muted-foreground">{document?.type.replaceAll("_", " ")}</p></td><td className="px-5 py-4 font-mono font-bold">{Number(movement.balance_after).toLocaleString("en-IN")}</td><td className="px-5 py-4 text-muted-foreground">{new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(movement.occurred_at))}</td></tr>; })}</tbody></table>{!movements.length ? <div className="grid min-h-72 place-items-center text-center"><div><ScrollText className="mx-auto size-10 text-primary" /><p className="mt-3 font-bold">The ledger is ready</p><p className="mt-1 text-sm text-muted-foreground">Validate a receipt, delivery, transfer or adjustment to create the first movement.</p></div></div> : null}</div></section></div>;
}
