import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Save } from "lucide-react";
import { FeedbackBanner } from "@/components/inventory/feedback-banner";
import { updateProductAction } from "@/features/products/actions";
import { loadProduct } from "@/features/products/queries";

const inputClass = "mt-2 min-h-11 w-full rounded-lg border bg-white px-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-blue-100";

export default async function EditProductPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { id } = await params; const query = await searchParams; const { product, categories, canManage, error } = await loadProduct(id); if (!product) notFound();
  const update = updateProductAction.bind(null, id);
  return <div className="mx-auto max-w-3xl space-y-6"><Link className="inline-flex items-center gap-2 text-sm font-bold text-primary" href="/products"><ArrowLeft className="size-4" />Back to products</Link><header><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Catalog record</p><h1 className="mt-1 text-3xl font-extrabold tracking-[-0.04em]">Edit product</h1><p className="mt-2 text-sm text-muted-foreground">Update product identity and reordering rules without changing ledger history.</p></header><FeedbackBanner error={(typeof query.error === "string" ? query.error : "") || (error ? "Product could not be loaded." : "") || undefined} success={typeof query.success === "string" ? query.success : undefined} /><section className="rounded-xl border bg-white p-6 shadow-sm">{canManage ? <form action={update} className="grid gap-5 sm:grid-cols-2"><label className="block text-xs font-bold sm:col-span-2">Product name<input className={inputClass} defaultValue={product.name} maxLength={160} name="name" required /></label><label className="block text-xs font-bold">SKU / code<input className={`${inputClass} font-mono uppercase`} defaultValue={product.sku} maxLength={40} name="sku" required /></label><label className="block text-xs font-bold">Category<select className={inputClass} defaultValue={product.category_id ?? ""} name="categoryId" required><option value="">Choose category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="block text-xs font-bold">Unit of measure<input className={inputClass} defaultValue={product.unit_of_measure} name="unitOfMeasure" required /></label><label className="block text-xs font-bold">Reorder level<input className={`${inputClass} font-mono`} defaultValue={String(product.reorder_level)} min="0" name="reorderLevel" step="0.001" type="number" required /></label><button className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-primary px-5 text-sm font-bold text-white sm:col-span-2" type="submit"><Save className="size-4" />Save product changes</button></form> : <p className="rounded-lg bg-slate-50 p-4 text-sm text-muted-foreground">Only inventory managers can edit products.</p>}</section></div>;
}
